apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: kz42dywzv-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/kz42dywzv-dotnet-basic-gitops